--글 저장 테이블 생성
  CREATE TABLE "T_ARTICLE1" 
   ("ARTICLENO" NUMBER(10,0), 
	"PARENTNO" NUMBER(10,0) DEFAULT 0, 
	"TITLE" VARCHAR2(500), 
	"CONTENT" VARCHAR2(4000), 
	"IMAGEFILENAME" VARCHAR2(30), 
	"WRITEDATE" DATE DEFAULT sysdate, 
	"MEMID" VARCHAR2(10), 
	"GROUPNO" NUMBER(10,0),
	CONSTRAINT FK_ARTICLE_MEMID FOREIGN KEY (MEMID) REFERENCES T_MEMBER1(MemId) 
   );


--회원 테이블
 CREATE TABLE "T_MEMBER1" 
   ("MEMID" VARCHAR2(10), 
	"PWD" VARCHAR2(10), 
	"NAME" VARCHAR2(50), 
	"EMAIL" VARCHAR2(50), 
	"JOINDATE" DATE DEFAULT sysdate
   ) ;


--댓글 저장 테이블 sql문
CREATE TABLE T_COMMENTS1(	
   COMMENTNO NUMBER(20) primary key,  --댓글 번호
   CCOMMENTNO NUMBER(20),  --댓글 그룹번호
   PCOMMENTNO NUMBER(20),  --부모 댓글 번호
   CONTENTS VARCHAR2(1000) NOT NULL ENABLE, 
   CREDATE DATE DEFAULT sysdate, 
   REPLYID VARCHAR2(20) NOT NULL ENABLE,
   ARTICLENO NUMBER(10,0) NOT NULL ENABLE,
	
   CONSTRAINT FK_COMMENTS_ARTICLENO FOREIGN KEY (ARTICLENO) REFERENCES T_ARTICLE1(ARTICLENO)  ON DELETE CASCADE ,
   CONSTRAINT FK_COMMENTS_REPLYID FOREIGN KEY (REPLYID) REFERENCES T_MEMBER1(MEMID)
);  