--댓글 저장 테이블 sql문
CREATE TABLE T_COMMENTS1(	
   COMMENTNO NUMBER(20) primary key,  --댓글 번호
   CCOMMENTNO NUMBER(20),  --댓글 그룹번호
   PCOMMENTNO NUMBER(20),  --부모 댓글 번호
   CONTENTS VARCHAR2(1000) NOT NULL ENABLE, 
   CREDATE DATE DEFAULT sysdate, 
   REPLYID VARCHAR2(20) NOT NULL ENABLE,
   ARTICLENO NUMBER(10,0) NOT NULL ENABLE,
	
   CONSTRAINT FK_COMMENTS_ARTICLENO FOREIGN KEY (ARTICLENO) REFERENCES T_ARTICLE1(ARTICLENO),
   CONSTRAINT FK_COMMENTS_REPLYID FOREIGN KEY (REPLYID) REFERENCES T_MEMBER1(MEMID)
);  